version: '3.0'

services:
  # 1. The Rasa Server
  rasa:
    image: rasa/rasa:3.6.2-full
    ports:
      - "5005:5005"
    volumes:
      - ./backend/rasa_bot:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - --debug
    depends_on:
      - action_server

  # 2. The Action Server
  action_server:
    build: ./backend/rasa_bot
    volumes:
      - ./backend/rasa_bot/actions:/app/actions
      - ./backend/web_api/project.db:/web_api/project.db
    ports:
      - "5055:5055"

  # 3. The Flask Web App
  flask_app:
    build: ./backend/web_api
    ports:
      - "5000:5000"
    volumes:
      - ./backend/web_api/project.db:/app/project.db
      - ./frontend/templates:/frontend/templates
      - ./frontend/static:/frontend/static
    environment:
      - FLASK_ENV=production
    depends_on:
      - rasa
